[project]
name = "seat-randomizer"
version = "1.0.0"
description = "A tool for randomizing student seating arrangements."
license = "MIT"
dependencies = ["pandas"]

[project.optional-dependencies]
dev = ["black", "ruff"]
